---
- name: Check if a folder called f1 is present if not create a file called f1
  hosts: all
  tasks:
    - name: Check for f1 dirctroy
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: Display output of above module
      debug:
        var: a
    - name: Create file f1 if dir f1 is not present
      file:
        name: /home/ubuntu/f1
        state: touch
      when: a.stat.exists == false

...
