---
- name: Create users and coppy file into user home dir
  hosts: all
  tasks:
    - name: create users
      user: 
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Ravi, b: 123, c: /home/Ravi}
        - {a: Abhi, b: 321, c: /home/Abhi}
    - name: Copy files into user home dir
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd, b: /home/Ravi}
        - {a: /etc/passwd, b: /home/Abhi}
...
