---
- name: Installing s/w applications
  hosts: all
  tasks:
    - name: Installing multiple s/w applications
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - tree
        - git
        - maven
...
