---
- name: Check for execute permissions & modify the permissions
  hosts: all
  tasks:
    - name: Get detailed info about file1
      stat:
        path: /tmp/file1
      register: b
    - name: Display output of the above module
      debug:
        var: b
    - name: check for execute permissions and change it
      file:
        name: /tmp/file1
        mode: 740
      when: b.state.executeable == false

