---
- name: Install/unistall s/w applications
  hosts: all
  vars:
    - a: tomcat9
    - b: present
    - c: no
  tasks:
    - name: Install/unintsall
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"

...
