---
- name: Installing s/w applications
  hosts: all
  tasks:
    - name: Installing multiple s/w applications
      apt:
        name: ["tree", "git", "maven"]
        state: absent
        update_cache: no  
...
